name: workshop-go-integration-test
on:
  push:
    branches: [main]

jobs:
  tests:
    name: "Integration testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up environment"
        run: docker compose -f docker/docker-compose.yml up --build --abort-on-container-exit
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Tests            # Name of the check run which will be created
          path: reports/*.xml    # Path to test results
          reporter: jest-junit        # Format of test results
