name: workshop-go-integration-test
on:
  push:
    branches: [main]

jobs:
  tests:
    name: "Integration testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up environment"
        run: docker compose -f docker/docker-compose.ci.yml up --build --abort-on-container-exit
